// import { UserProfile } from "./user";

// // Mock data for demonstration
// export const mockProfiles: UserProfile[] = [
//   {
//     id: "1",
//     fullName: "Sarah Johnson",
//     profession: "Full Stack Developer",
//     specialization: "React & Node.js",
//     location: "San Francisco, CA",
//     bio: "Passionate full-stack developer with 5+ years of experience building scalable web applications. I love creating intuitive user experiences and robust backend systems.",
//     skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
//     avatarUrl:
//       "https://images.unsplash.com/photo-1494790108755-2616b6cb8e9c?w=150&h=150&fit=crop&crop=face",
//     rating: 4.9,
//     completedProjects: 47,
//     gender: "female",
//     age: 28,
//     dateOfBirth: "1995-03-15",
//     linkedIn: "https://linkedin.com/in/sarahjohnson",
//     github: "https://github.com/sarahjohnson",
//     primaryEmail: "sarah.johnson@email.com",
//     phoneNumber: "1234567890",
//     salaryExpectation: 120000,
//     joinedDate: "2022-01-15",
//   },
//   {
//     id: "2",
//     fullName: "Marcus Chen",
//     profession: "UI/UX Designer",
//     specialization: "Mobile App Design",
//     location: "New York, NY",
//     bio: "Creative UI/UX designer specializing in mobile applications. I focus on creating beautiful, user-centered designs that drive engagement and conversions.",
//     skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
//     avatarUrl:
//       "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
//     rating: 4.8,
//     completedProjects: 32,
//     gender: "male",
//     age: 31,
//     dateOfBirth: "1992-08-22",
//     linkedIn: "https://linkedin.com/in/marcuschen",
//     github: "https://github.com/marcuschen",
//     primaryEmail: "marcus.chen@email.com",
//     phoneNumber: "1234567891",
//     salaryExpectation: 95000,
//     joinedDate: "2021-09-10",
//   },
//   {
//     id: "3",
//     fullName: "Emily Rodriguez",
//     profession: "Data Scientist",
//     specialization: "Machine Learning",
//     location: "Austin, TX",
//     bio: "Data scientist with expertise in machine learning and predictive analytics. I help businesses make data-driven decisions through advanced statistical modeling.",
//     skills: ["Python", "R", "TensorFlow", "SQL", "Tableau"],
//     avatarUrl:
//       "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
//     rating: 4.9,
//     completedProjects: 28,
//     gender: "female",
//     age: 26,
//     dateOfBirth: "1997-12-05",
//     linkedIn: "https://linkedin.com/in/emilyrodriguez",
//     github: "https://github.com/emilyrodriguez",
//     primaryEmail: "emily.rodriguez@email.com",
//     phoneNumber: "1234567892",
//     salaryExpectation: 110000,
//     joinedDate: "2022-06-20",
//   },
//   {
//     id: "4",
//     fullName: "David Thompson",
//     profession: "DevOps Engineer",
//     specialization: "Cloud Infrastructure",
//     location: "Seattle, WA",
//     bio: "DevOps engineer with extensive experience in cloud infrastructure and automation. I specialize in building scalable, reliable systems using modern DevOps practices.",
//     skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins"],
//     avatarUrl:
//       "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
//     rating: 4.7,
//     completedProjects: 39,
//     gender: "male",
//     age: 33,
//     dateOfBirth: "1990-06-18",
//     linkedIn: "https://linkedin.com/in/davidthompson",
//     github: "https://github.com/davidthompson",
//     primaryEmail: "david.thompson@email.com",
//     phoneNumber: "1234567893",
//     salaryExpectation: 130000,
//     joinedDate: "2021-03-12",
//   },
//   {
//     id: "5",
//     fullName: "Lisa Wang",
//     profession: "Product Manager",
//     specialization: "B2B SaaS",
//     location: "Boston, MA",
//     bio: "Strategic product manager with a track record of launching successful B2B SaaS products. I bridge the gap between technical teams and business objectives.",
//     skills: [
//       "Product Strategy",
//       "Agile",
//       "User Analytics",
//       "Roadmapping",
//       "Stakeholder Management",
//     ],
//     avatarUrl:
//       "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
//     rating: 4.8,
//     completedProjects: 23,
//     gender: "female",
//     age: 29,
//     dateOfBirth: "1994-11-30",
//     linkedIn: "https://linkedin.com/in/lisawang",
//     primaryEmail: "lisa.wang@email.com",
//     phoneNumber: "1234567894",
//     salaryExpectation: 140000,
//     joinedDate: "2022-02-28",
//   },
//   {
//     id: "6",
//     fullName: "Alex Kumar",
//     profession: "Mobile Developer",
//     specialization: "React Native",
//     location: "Chicago, IL",
//     bio: "Mobile developer passionate about creating seamless cross-platform experiences. I specialize in React Native and have built apps with millions of downloads.",
//     skills: ["React Native", "Swift", "Kotlin", "Firebase", "Redux"],
//     avatarUrl:
//       "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
//     rating: 4.9,
//     completedProjects: 34,
//     gender: "male",
//     age: 27,
//     dateOfBirth: "1996-04-12",
//     linkedIn: "https://linkedin.com/in/alexkumar",
//     github: "https://github.com/alexkumar",
//     primaryEmail: "alex.kumar@email.com",
//     phoneNumber: "1234567895",
//     salaryExpectation: 105000,
//     joinedDate: "2021-11-15",
//   },
// ];
